steps:
  - label: ':pipeline: :serverless: Playground'
    branches: '!main'
    env:
      STAGE: dev
      ACCOUNT_ID: '748446198525'
      DOMAIN_NAME: marketplace-sample-app.playground.agriwebb.io
      OAUTH_DOMAIN_NAME: auth.playground.agriwebb.com
      API_DOMAIN_NAME: api.playground.agriwebb.com
      DOCS_DOMAIN_NAME: docs.playground.agriwebb.io
      APP_DOMAIN_NAME: portal-staging.agriwebb.com
    command: ./.buildkite/scripts/deploy.sh
    agents:
      queue: 'yarn'

  - label: ':pipeline: :serverless: Staging'
    branches: 'main'
    env:
      STAGE: staging
      ACCOUNT_ID: '598117122758'
      DOMAIN_NAME: marketplace-sample-app.staging.agriwebb.io
      OAUTH_DOMAIN_NAME: auth.staging.agriwebb.com
      API_DOMAIN_NAME: api.staging.agriwebb.com
      DOCS_DOMAIN_NAME: docs.staging.agriwebb.io
      APP_DOMAIN_NAME: portal-staging.agriwebb.com
    command: ./.buildkite/scripts/deploy.sh
    agents:
      queue: 'yarn'

  - block: ':rocket: Deploy to Prod?'
    branches: 'main'
    prompt: 'Deploy to Prod?'

  - label: ':pipeline: :serverless: Prod'
    branches: 'main'
    env:
      STAGE: prod
      ACCOUNT_ID: '073065580947'
      DOMAIN_NAME: marketplace-sample-app.agriwebb.io
      OAUTH_DOMAIN_NAME: auth.agriwebb.com
      API_DOMAIN_NAME: api.agriwebb.com
      DOCS_DOMAIN_NAME: docs.agriwebb.io
      APP_DOMAIN_NAME: portal.agriwebb.com
    command: ./.buildkite/scripts/deploy.sh
    agents:
      queue: 'yarn'
